In [23]:
import json, os
import pandas as pd

In [24]:
data = json.load(open("../../data/prompts/openai-gpt-oss-120b-gen-prompts.json", 'r'))

In [25]:
len(data)

180

In [26]:
df = pd.DataFrame(data)

In [27]:
df

,n,task,task_description,dataset_description,language,generated_prompt,generation_meta
0,5,MIRACLRetrievalHardNegatives.v2,retrieval,,,Query for retrieval:,{'prompt': 'You are generating instruction pre...
1,5,MIRACLRetrievalHardNegatives.v2,retrieval,,,Retrieve relevant passage:,{'prompt': 'You are generating instruction pre...
2,5,MIRACLRetrievalHardNegatives.v2,retrieval,,,Encode this input for retrieval:,{'prompt': 'You are generating instruction pre...
3,5,MIRACLRetrievalHardNegatives.v2,retrieval,,,Search representation:,{'prompt': 'You are generating instruction pre...
4,5,MIRACLRetrievalHardNegatives.v2,retrieval,,,Text to be used in retrieval:,{'prompt': 'You are generating instruction pre...
...,...,...,...,...,...,...,...
175,5,MasakhaNEWSClusteringS2S,clustering,Clustering of news article headlines from Masa...,eng,Cluster MasakhaNEWS headlines in eng:,{'prompt': 'You are generating instruction pre...
176,5,MasakhaNEWSClusteringS2S,clustering,Clustering of news article headlines from Masa...,eng,Group similar news headlines (MasakhaNEWS) in ...,{'prompt': 'You are generating instruction pre...
177,5,MasakhaNEWSClusteringS2S,clustering,Clustering of news article headlines from Masa...,eng,Assign each MasakhaNEWS article title to a clu...,{'prompt': 'You are generating instruction pre...
178,5,MasakhaNEWSClusteringS2S,clustering,Clustering of news article headlines from Masa...,eng,Eng: perform clustering on MasakhaNEWS news he...,{'prompt': 'You are generating instruction pre...
179,5,MasakhaNEWSClusteringS2S,clustering,Clustering of news article headlines from Masa...,eng,Cluster representation for MasakhaNEWS headlin...,{'prompt': 'You are generating instruction pre...

In [28]:
df = df[['task', 'dataset_description', 'language', 'generated_prompt']].drop_duplicates()

In [29]:
df.shape

(180, 4)

In [33]:
def prepare_review_sample(row):
    return f"{row['task']}\nDesc:{row['dataset_description']}\nLang:\n{row['language']}\n\nGen Prompt:\n{row['generated_prompt']}"

df['text'] = df.apply(prepare_review_sample, axis=1)

In [34]:
df

,task,dataset_description,language,generated_prompt,text
0,MIRACLRetrievalHardNegatives.v2,,,Query for retrieval:,MIRACLRetrievalHardNegatives.v2\nDesc:\nLang:\...
1,MIRACLRetrievalHardNegatives.v2,,,Retrieve relevant passage:,MIRACLRetrievalHardNegatives.v2\nDesc:\nLang:\...
2,MIRACLRetrievalHardNegatives.v2,,,Encode this input for retrieval:,MIRACLRetrievalHardNegatives.v2\nDesc:\nLang:\...
3,MIRACLRetrievalHardNegatives.v2,,,Search representation:,MIRACLRetrievalHardNegatives.v2\nDesc:\nLang:\...
4,MIRACLRetrievalHardNegatives.v2,,,Text to be used in retrieval:,MIRACLRetrievalHardNegatives.v2\nDesc:\nLang:\...
...,...,...,...,...,...
175,MasakhaNEWSClusteringS2S,Clustering of news article headlines from Masa...,eng,Cluster MasakhaNEWS headlines in eng:,MasakhaNEWSClusteringS2S\nDesc:Clustering of n...
176,MasakhaNEWSClusteringS2S,Clustering of news article headlines from Masa...,eng,Group similar news headlines (MasakhaNEWS) in ...,MasakhaNEWSClusteringS2S\nDesc:Clustering of n...
177,MasakhaNEWSClusteringS2S,Clustering of news article headlines from Masa...,eng,Assign each MasakhaNEWS article title to a clu...,MasakhaNEWSClusteringS2S\nDesc:Clustering of n...
178,MasakhaNEWSClusteringS2S,Clustering of news article headlines from Masa...,eng,Eng: perform clustering on MasakhaNEWS news he...,MasakhaNEWSClusteringS2S\nDesc:Clustering of n...
179,MasakhaNEWSClusteringS2S,Clustering of news article headlines from Masa...,eng,Cluster representation for MasakhaNEWS headlin...,MasakhaNEWSClusteringS2S\nDesc:Clustering of n...

In [35]:
df.to_csv("../../data/manual_eval_prompts.csv")

In [36]:
df = df[df['task'] != "MasakhaNEWSClusteringS2S"]

In [38]:
df['n_words'] = df['generated_prompt'].apply(lambda x: len(x.split(" ")))

/var/folders/wb/kzt4j4sd26q1mv3lgfdq686c0000gp/T/ipykernel_71671/3283051606.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['n_words'] = df['generated_prompt'].apply(lambda x: len(x.split(" ")))

In [40]:
df['n_words'].describe()

count    165.000000
mean       5.248485
std        2.338454
min        2.000000
25%        4.000000
50%        5.000000
75%        6.000000
max       13.000000
Name: n_words, dtype: float64